name: CI

on: 
  pull_request:
    branches: [develop]

jobs:
  run-ci-commands:
    runs-on: ubuntu-latest
    steps:
      - name: cheching out
        uses: actions/checkout@v2
      - name: run tests
        run: |
          set -o pipefail xcodebuild test \
          -project bakoWorkflow.xcodeproj \
          -scheme bakoWorkflow \
          -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5'