name: CI

on: 
  pull_request:
    branches: [dev]

jobs:
  run-ci-commands:
    runs-on: macos-latest
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.3.app
      - name: Test - Fastlane tests
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: bakoworkflow.xcodeproj
          scheme: bakoWorkflowTests
          destination: "platform=iOS Simulator, id=dvtdevice-DVTiOSDeviceSimulator, name=iphone 8"
          action: test
