name: CI

on: 
  pull_request:
    branches:
      - dev

jobs:
  run-ci-commands:
    runs-on: ubuntu-latest
    steps:
      - name: cheching out
        uses: actions/checkout@v2
      - name: logging 
        run: echo "hello"
      - name: run tests
        run: |
          xcodebuild test \
          -project bakoWorkflow.xcodeproj \
          -scheme bakoWorkflow \
          -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5'
