name: CI

on: 
  pull_request:
    branches: [dev]

jobs:
  run-ci-commands:
    runs-on: macos-latest
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.3.app
      - name: "xcode test again"
        run: xcodebuild test -scheme bakoWorkflowTests -project bakoworkflow.xcodeproj -destination "platform=iOS Simulator,name=iphone 8"
